//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinamikCVProjesi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_UdemyAdminPanelliDinamikCVEntities : DbContext
    {
        public DB_UdemyAdminPanelliDinamikCVEntities()
            : base("name=DB_UdemyAdminPanelliDinamikCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Admin> TBL_Admin { get; set; }
        public virtual DbSet<TBL_Deneyimler> TBL_Deneyimler { get; set; }
        public virtual DbSet<TBL_Egitimler> TBL_Egitimler { get; set; }
        public virtual DbSet<TBL_Hakkımda> TBL_Hakkımda { get; set; }
        public virtual DbSet<TBL_Hobilerim> TBL_Hobilerim { get; set; }
        public virtual DbSet<TBL_İletisim> TBL_İletisim { get; set; }
        public virtual DbSet<TBL_Sertifikalar> TBL_Sertifikalar { get; set; }
        public virtual DbSet<TBL_Yetenek> TBL_Yetenek { get; set; }
        public virtual DbSet<TBL_Beceriler> TBL_Beceriler { get; set; }
    }
}
