//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinamikCVProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_Deneyimler
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Bu alan boş geçilemez !!!")]
        public string BASLIK { get; set; }
        public string ALTBASLIK { get; set; }
        public string ACIKLAMA { get; set; }
        public string TARİH { get; set; }
        public string Kullanılan_Diller { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
