//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinamikCVProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Yetenek
    {
        public int ID { get; set; }
        public string YETENEK { get; set; }
        public string YUZDE { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
