//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinamikCVProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Diller
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public Nullable<int> OKUMA { get; set; }
        public Nullable<int> YAZMA { get; set; }
        public Nullable<int> KONUSMA { get; set; }
        public Nullable<int> DİNLEME { get; set; }
    
        public virtual TBL_DilBilgisi TBL_DilBilgisi { get; set; }
        public virtual TBL_DilBilgisi TBL_DilBilgisi1 { get; set; }
        public virtual TBL_DilBilgisi TBL_DilBilgisi2 { get; set; }
        public virtual TBL_DilBilgisi TBL_DilBilgisi3 { get; set; }
    }
}
